"""add description to projects

Revision ID: af53db99e207
Revises:
Create Date: 2026-06-11 12:55:23.415055

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "af53db99e207"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_addons",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "project_programming_languages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "project_techs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "description", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True
        ),
        sa.Column("programming_language_id", sa.Integer(), nullable=False),
        sa.Column("project_tech_id", sa.Integer(), nullable=True),
        sa.Column("project_addon_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["programming_language_id"],
            ["project_programming_languages.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_addon_id"],
            ["project_addons.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_tech_id"],
            ["project_techs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "project_extras",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_programming_language_id", sa.Integer(), nullable=False),
        sa.Column("project_tech_id", sa.Integer(), nullable=True),
        sa.Column("project_addon_id", sa.Integer(), nullable=True),
        sa.Column("projects_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_addon_id"],
            ["project_addons.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_programming_language_id"],
            ["project_programming_languages.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_tech_id"],
            ["project_techs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["projects_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("project_extras")
    op.drop_table("projects")
    op.drop_table("project_techs")
    op.drop_table("project_programming_languages")
    op.drop_table("project_addons")
    # ### end Alembic commands ###
